name: Run Python Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Publish Unit Test Results
  	uses: EnricoMi/publish-unit-test-result-action@v1.38

